version: 2

defaults: &defaults
  docker:
    - image: circleci/node:12.16.1-stretch

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - admin-v3-node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - admin-v3-node-modules-{{ .Branch }}
      - run:
          name: Install NPM 
          command: sudo npm i -g npm@latest
      - run:
          name: Install NPM dependencies
          command: npm -v && npm ci
      - save_cache:
          key: admin-v3-node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: admin-v3-node-modules-{{ .Branch }}
          paths:
            - node_modules
  eslint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - admin-v3-node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - admin-v3-node-modules-{{ .Branch }}
      - run:
          name: Lint JavaScript
          command: npm run lint

  test-unit:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - admin-v3-node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - admin-v3-node-modules-{{ .Branch }}
      - run:
          name: Run Unit Tests
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-dependencies
      - eslint:
          requires:
            - install-dependencies
      - test-unit:
          requires:
            - install-dependencies